# Uncomment the next line to define a global platform for your project
 platform :ios, '10.0'
 use_frameworks!
target 'Android-Like-Tab' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  pod 'XLPagerTabStrip', '~> 8.0'

  # Pods for Android-Like-Tab

end
